// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(auth)/akses-ditolak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/akses-ditolak">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/akses-ditolak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/harian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/harian">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/harian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/kpi-saya/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/kpi-saya/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/kpi-saya/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/kpi-saya/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/kpi-saya">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/kpi-saya/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/notifikasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/notifikasi">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/notifikasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/pengaturan/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/pengaturan/[section]">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/pengaturan/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/pengaturan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/pengaturan">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/pengaturan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/rekap/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/rekap/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/rekap/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/rekap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/rekap">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/rekap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/review">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evidence/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evidence/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/export/monthly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/monthly">> = Specific
  const handler = {} as typeof import("../../../src/app/api/export/monthly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(workspace)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(workspace)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
