[program:kpi-worker]
command=/usr/bin/php /var/www/kpi-project/backend/artisan queue:work database --sleep=3 --tries=3 --timeout=120 --max-time=3600
directory=/var/www/kpi-project/backend
user=www-data
numprocs=1
process_name=%(program_name)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/var/log/supervisor/kpi-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
